version: "3.8"
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: "test-totvs-database"
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
